# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 550)
        # MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #464a43;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.topClock = QtWidgets.QLineEdit(self.centralwidget)
        self.topClock.setGeometry(QtCore.QRect(0, 0, 400, 250))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(95)
        font.setBold(True)
        font.setWeight(75)
        self.topClock.setFont(font)
        self.topClock.setAutoFillBackground(False)
        self.topClock.setStyleSheet("background-color: #aba98a; border-style: none; color: #464a43;")
        self.topClock.setAlignment(QtCore.Qt.AlignCenter)
        self.topClock.setReadOnly(True)
        
        self.topClock.setObjectName("topClock")
        self.bottomClock = QtWidgets.QLineEdit(self.centralwidget)
        self.bottomClock.setGeometry(QtCore.QRect(0, 300, 400, 250))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(95)
        font.setBold(True)
        font.setWeight(75)
        self.bottomClock.setFont(font)
        self.bottomClock.setStyleSheet("background-color: #aba98a; border-style: none; color: #464a43;")
        self.bottomClock.setAlignment(QtCore.Qt.AlignCenter)
        self.bottomClock.setObjectName("bottomClock")
        self.bottomClock.setReadOnly(True)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(60, 250, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("border-style: none; color: #aba98a;")
        self.startButton.setObjectName("startButton")
        self.restartButton = QtWidgets.QPushButton(self.centralwidget)
        self.restartButton.setGeometry(QtCore.QRect(0, 250, 50, 50))
        self.restartButton.setStyleSheet("border-style: solid;border-color: black; border-width: 1px; color: #aba98a;")
        self.restartButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("494817644_762227096260130_7019951372221094013_n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartButton.setIcon(icon)
        self.restartButton.setObjectName("restartButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 252, 150, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("border-style: none; color: #aba98a;")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(320, 250, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setStyleSheet("border-style: none; color: #aba98a; ")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChessClock"))
        self.topClock.setText(_translate("MainWindow", "10:00"))
        self.bottomClock.setText(_translate("MainWindow", "10:00"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.comboBox.setCurrentText(_translate("MainWindow", "10 min"))
        self.comboBox.setItemText(0, _translate("MainWindow", "10 min"))
        self.comboBox.setItemText(1, _translate("MainWindow", "5 min"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3 min"))
        self.checkBox.setText(_translate("MainWindow", "Sound"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
